import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { initializeApp } from 'firebase/app';
const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firebaseConfig = {
  apiKey: "AIzaSyByIoZqQx4cPa-BU6H1bAFsCMBC6U7KMrQ",
  authDomain: "kanban-board-ad650.firebaseapp.com",
  projectId: "kanban-board-ad650",
  storageBucket: "kanban-board-ad650.appspot.com",
  messagingSenderId: "1005242560703",
  appId: "1:1005242560703:web:d70f15b6250afea779160a"
};


const appAuth = initializeApp(firebaseConfig)


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export { appAuth };